name: Main CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup target add wasm32-unknown-unknown
      - name: Build and test contract
        run:  ./build.sh | cargo test
